version: "3"
services:

  wazuh-agent:
    image: wazuh-agent:amd-${WAZUH-AGENT_VERSION:-4.3.4}
    container_name: ${WAZUH-AGENT_HOSTNAME:-wazuh-agent}
    hostname: ${WAZUH-AGENT_HOSTNAME:-wazuh-agent}
    build:
      dockerfile: ./wazuh-agent/Dockerfile-${WAZUH-AGENT_ARCH:-amd64}
      tags:
        - wazuh-agent:amd-${WAZUH-AGENT_VERSION:-4.3.4}
      args:
        - WAZUH-AGENT_VERSION=${WAZUH-AGENT_VERSION:-4.3.4}
        - WAZUH-AGENT_ARCH=${WAZUH-AGENT_ARCH:-amd64}
    restart: ${RESTART_MODE:-unless-stopped}
    env_file:
      - ./.env
    environment:
      - JOIN_MANAGER=172.17.0.1 
      - JOIN_GROUPS=default,test
      - JOIN_PASSWORD=test123
    network_mode: host
    volumes:
       - /:/rootfs:ro
       - /etc/os-release:/etc/os-release
       - /var/run/docker.sock:/var/run/docker.sock
       - /var/ossec/ossec.conf:/var/ossec/etc/ossec.conf
       - /var/ossec/local_internal_options.conf:/var/ossec/etc/local_internal_options.conf
       - /var/ossec/client.keys:/var/ossec/etc/client.keys
      
networks:
  selkg-network:
#    external: true
    name: selkg-network
